data-mock
Koervege/GruApp pull request #1
Opened 2021-03-03 17:12 UTC by FernandoEspana

Data mock was created with user entity, motorcycle entity, supllier entity and tow entity; we use uuidv4 to generate entity id's automatically but  bind those id to create the relation with dependent entitys, example motorcycle depends of user, motrcycle have _idUser realtion on its object.

2021-03-03 18:57 UTC, simonhoyos requested changes
Muy buen PR! Un pequeño cambio y quedamos listos para hacer merge

2021-03-03 18:57 UTC, simonhoyos commented on src/pages/Login.js
> +        console.log( users );
No es buena idea dejar console.logs en el código que va para producción

2021-03-03 22:46 UTC, AlexisFranco approved these changes

2021-03-03 22:57 UTC, Koervege approved these changes

2021-03-03 22:57 UTC, pipesoto13 approved these changes

2021-03-04 12:49 UTC, simonhoyos approved these changes

2021-03-04 13:30 UTC, merged