Userinfopage
Koervege/GruApp pull request #13
Opened 2021-03-11 18:59 UTC by pipesoto13

![userpage](https://user-images.githubusercontent.com/51277503/110839725-e16f1180-8271-11eb-8865-71920d468e32.gif)

2021-03-11 19:01 UTC, simonhoyos requested changes

2021-03-11 19:01 UTC, simonhoyos commented on src/pages/UserInfo/styles.js
> +  border-radius: 5px;
Ojo con la identación

2021-03-11 21:26 UTC, pipesoto13 commented on src/pages/UserInfo/styles.js
> +  border-radius: 5px;
Me creerías si te digo que no sé como pasó eso? Acabo de revisar mi código y tenía esa parte bien indentada. Hice push de nuevo y me dice que todo está actualizado. Pero la indentación sigue así en github.

![image](https://user-images.githubusercontent.com/51277503/110856554-c9a18880-8285-11eb-9be2-3629c3e11b1e.png)

Voy a cambiarlo desde github directamente

2021-03-11 22:49 UTC, FernandoEspana approved these changes

2021-03-12 13:01 UTC, simonhoyos approved these changes

2021-03-12 13:01 UTC, simonhoyos commented on src/pages/UserInfo/styles.js
> +  border-radius: 5px;
😓 que loco eso jajajaja

2021-03-12 13:30 UTC, AlexisFranco approved these changes

2021-03-12 15:54 UTC, Koervege approved these changes

2021-03-12 15:57 UTC, merged