Login http
Koervege/GruApp pull request #16
Opened 2021-03-20 15:48 UTC by FernandoEspana

- Coneccion del componente login con el servidor.
- Guardar Token en local host
- Creacion de funcion auxiliar signin-http.js para limpiar codigo
- Try catch anidado para buscar en colecciones user/supplier
- Anterior se propone porque las dos colecciones no estan directamente relacionadas

2021-03-20 15:53 UTC, Koervege commented on src/pages/Login/Login.js
> +    } catch (err) {
Te falta el this.props.history.push()

2021-03-20 20:29 UTC, pipesoto13 approved these changes

2021-03-21 13:31 UTC, simonhoyos requested changes

2021-03-21 13:31 UTC, simonhoyos commented on src/pages/Login/Login.js
> +      try {
Alguna razón para anidar un try catch dentro del try catch?

2021-03-21 13:34 UTC, simonhoyos commented on src/pages/Login/Login.js
> +      try {
La lógica para saber si es un usuario o supplier debería estar mejor del lado del backend a la hora de hacer login

2021-03-22 13:24 UTC, Koervege approved these changes

2021-03-22 17:06 UTC, Koervege approved these changes

2021-03-23 15:16 UTC, simonhoyos approved these changes

2021-03-23 15:55 UTC, AlexisFranco approved these changes

2021-03-23 15:59 UTC, merged