Refactored Register, added Redux, added more validations
Koervege/GruApp pull request #26
Opened 2021-03-31 16:42 UTC by Koervege

- Register/index was changed to a functional component. Hooks were implemented.
- usersReducer created
- added more form validations to slightly improve usability
- Succesfully submitting the form now adds all of the new User's info to the global Redux state.

2021-03-31 16:50 UTC, FernandoEspana approved these changes

2021-04-01 00:40 UTC, pipesoto13 approved these changes

2021-04-01 09:52 UTC, AlexisFranco approved these changes

2021-04-01 12:32 UTC, simonhoyos requested changes

2021-04-01 12:32 UTC, simonhoyos commented on src/pages/Register/index.js
> +    } else history.push(`/userinfo/`);
Para mantener consistencia acá utilizaría la misma lógica que el if anterior. Dentro del if agrego un return y luego hago el history.push. Ese else se ve un poquitin feo 😅

2021-04-01 12:33 UTC, simonhoyos commented
Solo un pequeño comentario y luego queda listo para hacerle merge. Es más, mejor te lo apruebo de una vez y ya tu aplicas ese cambio para no bloquear el PR por ese detalle

2021-04-01 12:34 UTC, simonhoyos approved these changes

2021-04-01 14:02 UTC, merged