Userinfo updated, add images, improve behavior
Koervege/GruApp pull request #32
Opened 2021-04-06 22:43 UTC by pipesoto13

Se adiciona la lógica para poder recibir, mostrar y enviar archivos a bases de datos(imágenes en nuestro caso)
Se adiciona la librería sweet alert , para el renderizado de las alertas.
El funcionamiento de la pagina, cambia un poco por facilidad de implementación. Se adicionan botones de actualización a usuario y vehículos por separado, igual que el botón de agregar vehículo. Su lógica también se separa en sus respectivas funciones.
![userpage](https://user-images.githubusercontent.com/51277503/113786715-5877b880-96ff-11eb-9e81-0a84f7d4e0a6.gif)

2021-04-06 23:14 UTC, Koervege approved these changes

2021-04-06 23:15 UTC, AlexisFranco approved these changes

2021-04-06 23:19 UTC, FernandoEspana approved these changes

2021-04-07 12:08 UTC, simonhoyos requested changes

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +        console.log(error, 'No posee vehiculos registrados');
Sería bueno empezar a mostrar estos errores en la UI ya que están usando swal y reducir el uso de console.logs. Lo más importante es que el usuario pueda ver lo que está ocurriendo, y el usuario común no abre la consola para ver que está pasando con la app

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +    console.log(state.photo);
Borrar console.log

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +    const { data } = await axios({
Sería bueno envolver esto en un try/carch

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +    })
Si está usando async/await no es necesario usar then/catch

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +    await axios({
Trata de usar try/catch en las partes del código que pueden lanzar excepciones para que el código no se rompa

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/index.js
> +          {image && <ImgUser src={image} width="75" height="75" alt="profile preview" />}
A ImgUser no tienes que definirle el width y height en línea. Esto es mala practica y se recomienda hacerlo en el css (lo cual ya estás haciendo)

2021-04-07 12:08 UTC, simonhoyos commented on src/pages/UserInfo/styles.js
> +		height: 70px;
Ojo con la identación

2021-04-07 16:51 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +        console.log(error, 'No posee vehiculos registrados');
Hecho

2021-04-07 16:51 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +    console.log(state.photo);
Hecho

2021-04-07 16:51 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +    const { data } = await axios({
Hecho

2021-04-07 16:52 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +    })
Corregido, queda con try-catch

2021-04-07 16:53 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +          {image && <ImgUser src={image} width="75" height="75" alt="profile preview" />}
Corregido, lo había pasado y todo al CSS, pero se me olvidó borrarlo de esta línea. hecho

2021-04-07 16:55 UTC, pipesoto13 commented on src/pages/UserInfo/styles.js
> +		height: 70px;
Con esta si no he podido, segunda vez que me pasa. Intenté dejándole un espacio a la última línea y tampoco funciona. Cuando hago push a GitHub, este lo mueve. De nuevo sólo fué posible arreglarlo editando el código desde GitHub. Hecho

2021-04-07 16:56 UTC, pipesoto13 commented on src/pages/UserInfo/index.js
> +    await axios({
Hecho

2021-04-07 17:35 UTC, Koervege approved these changes

2021-04-08 12:00 UTC, simonhoyos approved these changes

2021-04-08 13:35 UTC, merged