Implemented modal for create service and fix bugs with de login
Koervege/GruApp pull request #34
Opened 2021-04-07 17:32 UTC by AlexisFranco

2021-04-07 17:35 UTC, Koervege approved these changes

2021-04-07 17:36 UTC, FernandoEspana approved these changes

2021-04-07 17:37 UTC, pipesoto13 approved these changes

2021-04-07 19:28 UTC, simonhoyos requested changes

2021-04-07 19:28 UTC, simonhoyos commented on src/components/Client/index.js
> +    }
En este archivo se están creando multiples compnentes y se está complicando mucho el código. Te recomiendo refactorizar el componente y dividirlo en multiples archivos

2021-04-07 19:28 UTC, simonhoyos commented on src/components/Provider/index.js
> +import moment from 'moment';
El uso de moment no es recomendado. La librería es pesada, muta constantemente los objetos. Incluso en la documentación de moment no recomiendan el uso de moment. Echale una mirada a date-fns

2021-04-07 19:28 UTC, simonhoyos commented on src/pages/Login/Login.js
> +/*     if(loading) return <p>Loading...</p>
No dejar comentarios en el código. Trata de no correr `git add .` y trata de revisar el código antes de subirlo para que no se pasen estas cosas

2021-04-07 21:33 UTC, simonhoyos commented on src/components/CreateServiceModal/index.js
> +        console.log(formValues)
ojo con los console.logs

2021-04-08 12:01 UTC, simonhoyos approved these changes

2021-04-08 13:36 UTC, merged