Changes in styles and Add Modal for the service progress
Koervege/GruApp pull request #46
Opened 2021-04-23 03:33 UTC by AlexisFranco

We did next changes:
- Styles in the services progress
- Checkbox of available tow, fix the funcionality.
- Changes and add funcionality in CreateServiceModal

We did next modals:
- Modal for the button Cancelar
- Modal for the button Aceptar
- Modal for the button Calificar

PD: I couldn't add video of the changes because the video size is big.

2021-04-23 12:21 UTC, simonhoyos requested changes

2021-04-23 12:21 UTC, simonhoyos commented on src/components/AddInformationModal/index.js
> +      console.log(rating);
Ojo con los console logs

2021-04-23 12:32 UTC, AlexisFranco commented on src/components/AddInformationModal/index.js
> +      console.log(rating);
Solucionado, pensé que había ya quitado todos los de prueba que había colocado

2021-04-23 14:03 UTC, FernandoEspana approved these changes

2021-04-23 16:35 UTC, simonhoyos approved these changes

2021-04-23 19:09 UTC, pipesoto13 approved these changes

2021-04-26 10:41 UTC, Koervege approved these changes

2021-04-26 11:12 UTC, merged