Create navbar component and its styles
Koervege/GruApp pull request #5
Opened 2021-03-05 20:25 UTC by pipesoto13

![image](https://user-images.githubusercontent.com/51277503/110169562-dc6c1700-7dc6-11eb-80b6-5ba8b6e49bed.png)

2021-03-05 20:28 UTC, AlexisFranco approved these changes

2021-03-05 21:33 UTC, simonhoyos requested changes

2021-03-05 21:33 UTC, simonhoyos commented on src/components/NavBar/index.js
> +                <img src="./images/moto.png" alt="logo" width="90" />
Esto todavía no lo hemos visto en el programa, pero las imagenes al usarlas de esta forma puede tener problemas a la hora de hacer el build. La mejor forma de usar imagenes locales sería:
1. importar la imagen
```javascript
import moto from './images/moto.png'
```

2. usar la variable que acabamos de importar como src de la imagen
```javascript
<img src={moto} alt="logo" />
```

Adicionalmente el width de la imagen sería mejor configurarlo a través del CSS y no por atributos

2021-03-06 00:02 UTC, FernandoEspana approved these changes

2021-03-06 00:33 UTC, AlexisFranco approved these changes

2021-03-06 00:34 UTC, Koervege approved these changes

2021-03-06 00:38 UTC, pipesoto13 commented on src/components/NavBar/index.js
> +                <img src="./images/moto.png" alt="logo" width="90" />
Se cambió la imagen por un ícono desde fontwaesome.

2021-03-07 02:22 UTC, simonhoyos approved these changes

2021-03-07 16:56 UTC, merged