Register form page
Koervege/GruApp pull request #6
Opened 2021-03-06 19:10 UTC by Koervege

Created a form for the register page with styled components made by Fernando.
![screenshotRegister](https://user-images.githubusercontent.com/74723336/110218101-c07b7a80-7e85-11eb-802c-98b7e96d4c39.png)

2021-03-06 19:21 UTC, pipesoto13 approved these changes

2021-03-06 19:57 UTC, FernandoEspana approved these changes

2021-03-06 20:30 UTC, AlexisFranco approved these changes

2021-03-07 02:24 UTC, simonhoyos requested changes

2021-03-07 02:24 UTC, simonhoyos commented on yarn.lock
> +<<<<<<< HEAD
Cuidado, subiste los conflictos de este archivo

2021-03-07 14:26 UTC, Koervege commented on yarn.lock
> +<<<<<<< HEAD
Cómo los remuevo?

2021-03-07 20:47 UTC, simonhoyos commented on yarn.lock
> +<<<<<<< HEAD
En este caso es muy fácil. Puedes borrar el archivo yarn.lock y autogenerar uno nuevo corriendo el comando `yarn install` o `yarn`. Para que no te ocurra en el futuro puedes leer siempre los mensajes que te muestra git, es importante leerlos todos pero los conflictos es muy fácil identificarlos cuando haces `git pull`

2021-03-07 20:54 UTC, Koervege commented on yarn.lock
> +<<<<<<< HEAD
Ya lo arreglé. Gracias

2021-03-08 13:07 UTC, simonhoyos approved these changes

2021-03-08 15:35 UTC, merged