NavBar Component changed to styled-component. .css file deleted
Koervege/GruApp pull request #9
Opened 2021-03-08 03:19 UTC by pipesoto13

2021-03-08 04:30 UTC, FernandoEspana approved these changes

2021-03-08 12:19 UTC, Koervege approved these changes

2021-03-08 12:48 UTC, AlexisFranco approved these changes

2021-03-08 13:10 UTC, simonhoyos requested changes

2021-03-08 13:10 UTC, simonhoyos commented on src/components/NavBar/index.js
> +const ATags = styled.a`
Usar anchors en la página va a hacer que se refresque la página y se pierda el estado de los componentes. Para que no ocurra esto puedes usar el componente Link de react-router-dom

2021-03-08 13:10 UTC, simonhoyos commented on src/components/NavBar/index.js
> +const Nav = styled.nav`
Todos los componentes de estilos los puedes mover a otro archivo y aprovechar el export/import para limpiar un poco el componente principal del archivo

2021-03-09 04:13 UTC, pipesoto13 commented
![navbar](https://user-images.githubusercontent.com/51277503/110417450-a6978e80-8063-11eb-8423-79fb0a1ede63.gif)

2021-03-09 13:18 UTC, simonhoyos requested changes

2021-03-09 13:18 UTC, simonhoyos commented on src/components/NavBar/styles.js
> +display: flex;
Ojo con la identación. Todas las propiedades de css en este caso deberían tener un nivel adicional de identación

2021-03-09 13:19 UTC, simonhoyos commented
En este caso se están cambiando o se esta haciendo una migración de los estilos. Mi recomendación es que agregues siempre imagenes al PR para mostrar como se veía la app antes y después para que el revisor sepa que todo está funcionando como debería

2021-03-09 13:20 UTC, simonhoyos commented
> ![navbar](https://user-images.githubusercontent.com/51277503/110417450-a6978e80-8063-11eb-8423-79fb0a1ede63.gif)

Súper bien el vídeo. Puedes editar el PR y agregarlo en la descripción

2021-03-09 15:37 UTC, simonhoyos approved these changes

2021-03-09 15:39 UTC, merged